// stubs/spa-vue/frontend/src/pages/Category.vue
<template>
    <p class="shop-crumb"><RouterLink to="/catalog">Каталог</RouterLink> / {{ category.name }}</p>
    <h1 class="shop-h1">{{ category.name }}</h1>
    <div class="shop-grid-products">
        <ProductCard v-for="product in products.data" :key="product.id" :product="product" />
    </div>
</template>

<script setup>
import { onMounted, reactive } from 'vue';
import { useRoute } from 'vue-router';
import { api } from '../api';
import ProductCard from '../components/ProductCard.vue';

const route = useRoute();
const category = reactive({ name: '' });
const products = reactive({ data: [] });

onMounted(async () => {
    const { data } = await api.get(`/api/shop/category/${route.params.slug}`);
    Object.assign(category, data.category);
    Object.assign(products, data.products);
});
</script>

// stubs/inertia-react/resources/js/Pages/Category.jsx
import { Link } from '@inertiajs/react';
import ProductCard from '../Components/ProductCard';

export default function Category({ category, products }) {
    return (
        <>
            <p className="shop-crumb"><Link href="/catalog">Каталог</Link> / {category.name}</p>
            <h1 className="shop-h1">{category.name}</h1>
            {category.description && <p className="shop-lead">{category.description}</p>}
            <div className="shop-grid-products">
                {(products.data || []).map((product) => <ProductCard key={product.id} product={product} />)}
            </div>
        </>
    );
}
