// stubs/spa-vue/frontend/src/pages/Checkout.vue
<template>
    <h1 class="shop-h1">Оформление заказа</h1>
    <form class="shop-form" @submit.prevent="submit">
        <label>Имя <input v-model="form.name" required></label>
        <label>Телефон <input v-model="form.phone" required></label>
        <label>Email <input v-model="form.email" type="email"></label>
        <label>Адрес <textarea v-model="form.address" required></textarea></label>
        <label>Комментарий <textarea v-model="form.comment"></textarea></label>
        <button class="shop-btn" type="submit">Подтвердить заказ</button>
    </form>
</template>

<script setup>
import { inject, reactive } from 'vue';
import { useRouter } from 'vue-router';
import { api } from '../api';

const shop = inject('shop');
const router = useRouter();
const form = reactive({
    name: shop?.auth?.user?.name || '',
    phone: '',
    email: shop?.auth?.user?.email || '',
    address: '',
    comment: '',
});

async function submit() {
    const { data } = await api.post('/api/shop/checkout', form);
    await router.push(`/checkout/success/${data.order.id}`);
}
</script>

// stubs/inertia-react/resources/js/Pages/Checkout.jsx
import { router } from '@inertiajs/react';
import { useState } from 'react';

export default function Checkout({ lines = [], total_formatted, user }) {
    const [form, setForm] = useState({
        name: user?.name || '',
        phone: '',
        email: user?.email || '',
        address: '',
        comment: '',
    });

    const onChange = (key) => (e) => setForm({ ...form, [key]: e.target.value });

    return (
        <>
            <h1 className="shop-h1">Оформление заказа</h1>
            <div className="shop-checkout">
                <form className="shop-form" onSubmit={(e) => { e.preventDefault(); router.post('/checkout', form); }}>
                    <label>Имя <input value={form.name} onChange={onChange('name')} required /></label>
                    <label>Телефон <input value={form.phone} onChange={onChange('phone')} required /></label>
                    <label>Email <input type="email" value={form.email} onChange={onChange('email')} /></label>
                    <label>Адрес доставки <textarea rows="3" value={form.address} onChange={onChange('address')} required /></label>
                    <label>Комментарий <textarea rows="3" value={form.comment} onChange={onChange('comment')} /></label>
                    <button className="shop-btn" type="submit">Подтвердить заказ</button>
                </form>
                <aside className="shop-summary">
                    <h2>Ваш заказ</h2>
                    {lines.map((line) => (
                        <div key={line.id} className="shop-summary-row">
                            <span>{line.name} × {line.qty}</span>
                            <span>{line.sum_formatted}</span>
                        </div>
                    ))}
                    <div className="shop-summary-row shop-summary-total">
                        <span>Итого</span>
                        <strong>{total_formatted}</strong>
                    </div>
                </aside>
            </div>
        </>
    );
}
