// stubs/inertia-vue/resources/js/Pages/Success.vue
<template>
    <div class="shop-success">
        <h1 class="shop-h1">Спасибо!</h1>
        <p>Заказ <strong>{{ order.number }}</strong> принят. Мы свяжемся с вами для подтверждения.</p>
        <p>Сумма: {{ order.total_formatted }}</p>
        <Link href="/" class="shop-btn">На главную</Link>
    </div>
</template>

<script setup>
import { Link } from '@inertiajs/vue3';

defineProps({ order: Object });
</script>

// stubs/inertia-react/resources/js/Pages/Success.jsx
import { Link } from '@inertiajs/react';

export default function Success({ order }) {
    return (
        <div className="shop-success">
            <h1 className="shop-h1">Спасибо!</h1>
            <p>Заказ <strong>{order.number}</strong> принят. Мы свяжемся с вами для подтверждения.</p>
            <p>Сумма: {order.total_formatted}</p>
            <Link href="/" className="shop-btn">На главную</Link>
        </div>
    );
}
