// stubs/inertia-react/resources/js/Pages/Checkout.jsx
import { router } from '@inertiajs/react';
import { useState } from 'react';

export default function Checkout({ lines = [], total_formatted, user }) {
    const [form, setForm] = useState({
        name: user?.name || '',
        phone: '',
        email: user?.email || '',
        address: '',
        comment: '',
    });

    const onChange = (key) => (e) => setForm({ ...form, [key]: e.target.value });

    return (
        <>
            <h1 className="shop-h1">Оформление заказа</h1>
            <div className="shop-checkout">
                <form className="shop-form" onSubmit={(e) => { e.preventDefault(); router.post('/checkout', form); }}>
                    <label>Имя <input value={form.name} onChange={onChange('name')} required /></label>
                    <label>Телефон <input value={form.phone} onChange={onChange('phone')} required /></label>
                    <label>Email <input type="email" value={form.email} onChange={onChange('email')} /></label>
                    <label>Адрес доставки <textarea rows="3" value={form.address} onChange={onChange('address')} required /></label>
                    <label>Комментарий <textarea rows="3" value={form.comment} onChange={onChange('comment')} /></label>
                    <button className="shop-btn" type="submit">Подтвердить заказ</button>
                </form>
                <aside className="shop-summary">
                    <h2>Ваш заказ</h2>
                    {lines.map((line) => (
                        <div key={line.id} className="shop-summary-row">
                            <span>{line.name} × {line.qty}</span>
                            <span>{line.sum_formatted}</span>
                        </div>
                    ))}
                    <div className="shop-summary-row shop-summary-total">
                        <span>Итого</span>
                        <strong>{total_formatted}</strong>
                    </div>
                </aside>
            </div>
        </>
    );
}

// stubs/inertia-vue/resources/js/Pages/Checkout.vue
<template>
    <h1 class="shop-h1">Оформление заказа</h1>
    <p class="shop-muted">Оплата при получении. После отправки заявки с вами свяжется менеджер.</p>
    <div class="shop-checkout">
        <form class="shop-form" @submit.prevent="submit">
            <label>Имя <input v-model="form.name" required></label>
            <label>Телефон <input v-model="form.phone" required></label>
            <label>Email <input v-model="form.email" type="email"></label>
            <label>Адрес доставки <textarea v-model="form.address" rows="3" required></textarea></label>
            <label>Комментарий <textarea v-model="form.comment" rows="3"></textarea></label>
            <button class="shop-btn" type="submit">Подтвердить заказ</button>
        </form>
        <aside class="shop-summary">
            <h2>Ваш заказ</h2>
            <div v-for="line in lines" :key="line.id" class="shop-summary-row">
                <span>{{ line.name }} × {{ line.qty }}</span>
                <span>{{ line.sum_formatted }}</span>
            </div>
            <div class="shop-summary-row shop-summary-total">
                <span>Итого</span>
                <strong>{{ total_formatted }}</strong>
            </div>
        </aside>
    </div>
</template>

<script setup>
import { reactive } from 'vue';
import { router } from '@inertiajs/vue3';

const props = defineProps({ lines: Array, total_formatted: String, user: Object });
const form = reactive({
    name: props.user?.name || '',
    phone: '',
    email: props.user?.email || '',
    address: '',
    comment: '',
});

function submit() {
    router.post('/checkout', form);
}
</script>
