// stubs/inertia-react/resources/js/Pages/Home.jsx
import { Link } from '@inertiajs/react';
import ProductCard from '../Components/ProductCard';

export default function Home({ site, categories = [], products = [] }) {
    return (
        <>
            <section className="shop-hero">
                <p className="shop-kicker">Интернет-магазин</p>
                <h1>{site?.name || 'Магазин'}</h1>
                <p className="shop-lead">{site?.description}</p>
                <Link href="/catalog" className="shop-btn">Смотреть каталог</Link>
            </section>
            <section className="mt-12">
                <h2 className="shop-h2">Категории</h2>
                <div className="shop-grid-cats">
                    {categories.map((category) => (
                        <Link key={category.id} className="shop-cat-card" href={`/category/${category.slug}`}>
                            <strong>{category.name}</strong>
                            <span>{category.products_count} товаров</span>
                        </Link>
                    ))}
                </div>
            </section>
            <section className="mt-12">
                <h2 className="shop-h2">Популярные товары</h2>
                <div className="shop-grid-products">
                    {products.map((product) => <ProductCard key={product.id} product={product} />)}
                </div>
            </section>
        </>
    );
}

// stubs/inertia-vue/resources/js/Pages/Home.vue
<template>
    <section class="shop-hero">
        <p class="shop-kicker">Интернет-магазин</p>
        <h1>{{ site?.name || 'Магазин' }}</h1>
        <p class="shop-lead">{{ site?.description }}</p>
        <Link href="/catalog" class="shop-btn">Смотреть каталог</Link>
    </section>
    <section class="mt-12">
        <h2 class="shop-h2">Категории</h2>
        <div class="shop-grid-cats">
            <Link v-for="category in categories" :key="category.id" class="shop-cat-card" :href="`/category/${category.slug}`">
                <strong>{{ category.name }}</strong>
                <span>{{ category.products_count }} товаров</span>
            </Link>
        </div>
    </section>
    <section class="mt-12">
        <h2 class="shop-h2">Популярные товары</h2>
        <div class="shop-grid-products">
            <ProductCard v-for="product in products" :key="product.id" :product="product" />
        </div>
    </section>
</template>

<script setup>
import { Link } from '@inertiajs/vue3';
import ProductCard from '../Components/ProductCard.vue';

defineProps({ site: Object, categories: Array, products: Array });
</script>
