// stubs/inertia-react/resources/js/Pages/Product.jsx
import { Link, router } from '@inertiajs/react';
import { useState } from 'react';
import ProductCard from '../Components/ProductCard';

export default function Product({ product }) {
    const [qty, setQty] = useState(1);

    return (
        <>
            <p className="shop-crumb">
                <Link href="/catalog">Каталог</Link>
                {product.category && <> / <Link href={`/category/${product.category.slug}`}>{product.category.name}</Link></>}
                / {product.name}
            </p>
            <div className="shop-product-page">
                <div>
                    {product.gallery?.length ? product.gallery.map((image) => (
                        <a key={image.url} href={image.url}><img src={image.url} alt={product.name} /></a>
                    )) : <div className="shop-photo-empty shop-photo-lg">Нет фото</div>}
                </div>
                <div>
                    <h1 className="shop-h1">{product.name}</h1>
                    <div className="shop-price-row shop-price-lg">
                        <strong>{product.price_formatted}</strong>
                    </div>
                    <p className="mt-4">{product.description}</p>
                    <div className="shop-add-form">
                        <label>Количество
                            <input type="number" min="1" value={qty} onChange={(e) => setQty(Number(e.target.value))} />
                        </label>
                        <button className="shop-btn" type="button" disabled={!product.in_stock} onClick={() => router.post(`/cart/add/${product.id}`, { qty })}>
                            {product.in_stock ? 'Добавить в корзину' : 'Нет в наличии'}
                        </button>
                    </div>
                </div>
            </div>
            {product.related?.length > 0 && (
                <>
                    <h2 className="shop-h2 mt-12">Похожие товары</h2>
                    <div className="shop-grid-products">
                        {product.related.map((item) => <ProductCard key={item.id} product={item} />)}
                    </div>
                </>
            )}
        </>
    );
}

// stubs/inertia-vue/resources/js/Pages/Product.vue
<template>
    <p class="shop-crumb">
        <Link href="/catalog">Каталог</Link>
        <template v-if="product.category"> / <Link :href="`/category/${product.category.slug}`">{{ product.category.name }}</Link></template>
        / {{ product.name }}
    </p>
    <div class="shop-product-page">
        <div>
            <div v-if="product.gallery?.length" class="product-swiper">
                <a v-for="image in product.gallery" :key="image.url" :href="image.url">
                    <img :src="image.url" :alt="product.name">
                </a>
            </div>
            <div v-else class="shop-photo-empty shop-photo-lg">Нет фото</div>
        </div>
        <div>
            <h1 class="shop-h1">{{ product.name }}</h1>
            <p v-if="product.sku" class="shop-muted">Артикул: {{ product.sku }}</p>
            <div class="shop-price-row shop-price-lg">
                <strong>{{ product.price_formatted }}</strong>
                <s v-if="product.old_price_formatted">{{ product.old_price_formatted }}</s>
            </div>
            <p class="mt-4">{{ product.description }}</p>
            <p class="mt-3 shop-muted">На складе: {{ product.quantity }} шт.</p>
            <div class="shop-add-form">
                <label>Количество
                    <input v-model.number="qty" type="number" min="1" :max="product.quantity || 1">
                </label>
                <button class="shop-btn" type="button" :disabled="!product.in_stock" @click="add">
                    {{ product.in_stock ? 'Добавить в корзину' : 'Нет в наличии' }}
                </button>
            </div>
        </div>
    </div>
    <h2 v-if="product.related?.length" class="shop-h2 mt-12">Похожие товары</h2>
    <div v-if="product.related?.length" class="shop-grid-products">
        <ProductCard v-for="item in product.related" :key="item.id" :product="item" />
    </div>
</template>

<script setup>
import { ref } from 'vue';
import { Link, router } from '@inertiajs/vue3';
import ProductCard from '../Components/ProductCard.vue';

const props = defineProps({ product: Object });
const qty = ref(1);

function add() {
    router.post(`/cart/add/${props.product.id}`, { qty: qty.value });
}
</script>
