// stubs/spa-vue/frontend/src/pages/Login.vue
<template>
    <h1 class="shop-h1">Вход</h1>
    <form class="shop-form" style="max-width: 28rem" @submit.prevent="submit">
        <label>Email <input v-model="form.email" type="email" required></label>
        <label>Пароль <input v-model="form.password" type="password" required></label>
        <button class="shop-btn" type="submit">Войти</button>
    </form>
    <div class="shop-social">
        <a class="shop-btn-ghost" href="/auth/yandex/redirect">Яндекс</a>
        <a class="shop-btn-ghost" href="/auth/vkontakte/redirect">ВКонтакте</a>
    </div>
    <p class="mt-4"><RouterLink to="/register">Регистрация</RouterLink></p>
</template>

<script setup>
import { inject, reactive } from 'vue';
import { useRouter } from 'vue-router';
import { api } from '../api';

const router = useRouter();
const refreshShop = inject('refreshShop');
const form = reactive({ email: '', password: '' });

async function submit() {
    await api.post('/api/login', form);
    await refreshShop?.();
    await router.push('/');
}
</script>

// stubs/inertia-react/resources/js/Pages/Auth/Login.jsx
import { Link, router } from '@inertiajs/react';
import { useState } from 'react';

export default function Login() {
    const [form, setForm] = useState({ email: '', password: '', remember: false });

    return (
        <>
            <h1 className="shop-h1">Вход</h1>
            <form className="shop-form" style={{ maxWidth: '28rem' }} onSubmit={(e) => { e.preventDefault(); router.post('/login', form); }}>
                <label>Email <input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label>
                <label>Пароль <input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /></label>
                <button className="shop-btn" type="submit">Войти</button>
            </form>
            <div className="shop-social">
                <p className="shop-muted">Или войти через</p>
                <div className="shop-social-row">
                    <a className="shop-btn-ghost" href="/auth/yandex/redirect">Яндекс</a>
                    <a className="shop-btn-ghost" href="/auth/vkontakte/redirect">ВКонтакте</a>
                </div>
            </div>
            <p className="mt-4">Нет аккаунта? <Link href="/register">Регистрация</Link></p>
        </>
    );
}
