// stubs/spa-vue/frontend/src/pages/Register.vue
<template>
    <h1 class="shop-h1">Регистрация</h1>
    <form class="shop-form" style="max-width: 28rem" @submit.prevent="submit">
        <label>Имя <input v-model="form.name" required></label>
        <label>Email <input v-model="form.email" type="email" required></label>
        <label>Пароль <input v-model="form.password" type="password" required></label>
        <label>Повтор пароля <input v-model="form.password_confirmation" type="password" required></label>
        <button class="shop-btn" type="submit">Создать аккаунт</button>
    </form>
    <div class="shop-social">
        <a class="shop-btn-ghost" href="/auth/yandex/redirect">Яндекс</a>
        <a class="shop-btn-ghost" href="/auth/vkontakte/redirect">ВКонтакте</a>
    </div>
</template>

<script setup>
import { inject, reactive } from 'vue';
import { useRouter } from 'vue-router';
import { api } from '../api';

const router = useRouter();
const refreshShop = inject('refreshShop');
const form = reactive({ name: '', email: '', password: '', password_confirmation: '' });

async function submit() {
    await api.post('/api/register', form);
    await refreshShop?.();
    await router.push('/');
}
</script>

// stubs/inertia-react/resources/js/Pages/Auth/Register.jsx
import { Link, router } from '@inertiajs/react';
import { useState } from 'react';

export default function Register() {
    const [form, setForm] = useState({ name: '', email: '', password: '', password_confirmation: '' });

    return (
        <>
            <h1 className="shop-h1">Регистрация</h1>
            <form className="shop-form" style={{ maxWidth: '28rem' }} onSubmit={(e) => { e.preventDefault(); router.post('/register', form); }}>
                <label>Имя <input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label>
                <label>Email <input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label>
                <label>Пароль <input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /></label>
                <label>Повтор пароля <input type="password" value={form.password_confirmation} onChange={(e) => setForm({ ...form, password_confirmation: e.target.value })} required /></label>
                <button className="shop-btn" type="submit">Создать аккаунт</button>
            </form>
            <div className="shop-social">
                <p className="shop-muted">Или войти через</p>
                <div className="shop-social-row">
                    <a className="shop-btn-ghost" href="/auth/yandex/redirect">Яндекс</a>
                    <a className="shop-btn-ghost" href="/auth/vkontakte/redirect">ВКонтакте</a>
                </div>
            </div>
            <p className="mt-4">Уже есть аккаунт? <Link href="/login">Войти</Link></p>
        </>
    );
}
