// stubs/spa-vue/frontend/src/pages/Home.vue
<template>
    <section class="shop-hero">
        <h1>{{ data.site?.name || 'Магазин' }}</h1>
        <p class="shop-lead">{{ data.site?.description }}</p>
        <RouterLink to="/catalog" class="shop-btn">Смотреть каталог</RouterLink>
    </section>
    <section class="mt-12">
        <h2 class="shop-h2">Категории</h2>
        <div class="shop-grid-cats">
            <RouterLink v-for="category in data.categories" :key="category.id" class="shop-cat-card" :to="`/category/${category.slug}`">
                <strong>{{ category.name }}</strong>
                <span>{{ category.products_count }} товаров</span>
            </RouterLink>
        </div>
    </section>
    <section class="mt-12">
        <h2 class="shop-h2">Популярные товары</h2>
        <div class="shop-grid-products">
            <ProductCard v-for="product in data.products" :key="product.id" :product="product" />
        </div>
    </section>
</template>

<script setup>
import { onMounted, reactive } from 'vue';
import { api } from '../api';
import ProductCard from '../components/ProductCard.vue';

const data = reactive({ site: {}, categories: [], products: [] });

onMounted(async () => {
    const { data: payload } = await api.get('/api/shop/home');
    Object.assign(data, payload);
});
</script>

// stubs/spa-react/frontend/src/pages/Home.jsx
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api';
import ProductCard from '../components/ProductCard';

export default function Home() {
    const [data, setData] = useState({ site: {}, categories: [], products: [] });

    useEffect(() => {
        api.get('/api/shop/home').then((r) => setData(r.data));
    }, []);

    return (
        <>
            <section className="shop-hero">
                <h1>{data.site?.name || 'Магазин'}</h1>
                <p className="shop-lead">{data.site?.description}</p>
                <Link to="/catalog" className="shop-btn">Смотреть каталог</Link>
            </section>
            <section className="mt-12">
                <h2 className="shop-h2">Категории</h2>
                <div className="shop-grid-cats">
                    {(data.categories || []).map((category) => (
                        <Link key={category.id} className="shop-cat-card" to={`/category/${category.slug}`}>
                            <strong>{category.name}</strong>
                            <span>{category.products_count} товаров</span>
                        </Link>
                    ))}
                </div>
            </section>
            <section className="mt-12">
                <h2 className="shop-h2">Популярные товары</h2>
                <div className="shop-grid-products">
                    {(data.products || []).map((product) => (
                        <ProductCard key={product.id} product={product} />
                    ))}
                </div>
            </section>
        </>
    );
}
